# Generated by Django 3.1.4 on 2020-12-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190924_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Reserved'), ('m', 'Maintainance'), ('a', 'Available'), ('0', 'On loan')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
